### ISSUE TITLE
The Readme Updates

### ISSUE THREAD

**Issue by pragyaasapkota** [Asilshah006/--Hacktoberfest_2022#27]
The Readme could be more updated with the mention of: -

1. What is hacktoberfest?
2. What is the repo requirements?
3. How to contribute?
4. The rules
5. The Code of Conduct
6. Contributors mention

**Comment by pragyaasapkota** [comment]
Please assign me in the issue and I will prepare a documentation on this.

**Comment by pragyaasapkota** [comment]
@Asilshah006

**Comment by Asilshah006** [comment]
Assigned

**Comment by pragyaasapkota** [comment]
@Asilshah006 
Please assign me on the [Adding Code of conducts](https://github.com/Asilshah006/--Hacktoberfest_2022/issues/26) and [The more clear CONTRIBUTING.md](https://github.com/Asilshah006/--Hacktoberfest_2022/issues/28) first. 
First we need to update the code of conduct and them contributing.md and then the readme updates at last with the links from code of conducts and contributing.md

**Comment by pragyaasapkota** [comment]
Thank you!!
