### ISSUE TITLE
The more clear CONTRIBUTING.md

### ISSUE THREAD

**Issue by pragyaasapkota** [Asilshah006/--Hacktoberfest_2022#28]
The CONTRIBUTING.md file is not as clear as it should be.

**Comment by pragyaasapkota** [comment]
Please assign me and I will prepare a clear document on the CONTRIBUTING.md file.

**Comment by NotAtitYet** [comment]
Please assign this to me. I want to contribute to this.

**Comment by pragyaasapkota** [comment]
@Asilshah006 
Please assign me on this!!

**Comment by pragyaasapkota** [comment]
Thank you!!
